# Generated by Django 4.0.4 on 2023-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint', '0002_remove_carbonfootprint_carbon_footprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprint',
            name='chat_gpt_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
